defaults: &defaults
  admin_emails:
    - "linyaoyi011@gmail.com"
  time_zone: 'Beijing'
  default_locale: 'zh-CN'
  faye_server: "http://127.0.0.1:9292/faye"
  faye_token: "123456"
  weibo_key: '15461246'
  weibo_secret: '516b6ef690d35075e98ed114efdc7fe4'
  logo_home: "uploads/photo/image/16/LOGO-Home_page.png"
  logo_welcome: "uploads/photo/image/17/LOGO-Welcome_page.png"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
