defaults: &defaults
  admin_emails:
    - "linyaoyi011@gmail.com"
  time_zone: 'Beijing'
  default_locale: 'zh-CN'
  faye_server: "http://127.0.0.1:9292/faye"
  faye_token: "123456"
  weibo_key: '1555320033'
  weibo_secret: '24362b95d5bab896da9508692c367782'
  twitter_key: 'lhu02O5rSIVJKye9ehoklHFI0'
  twitter_secret: "HcmKJFhh4D4AnFZqejfMSnWbalWD1VPbuB840MpOHTUZz6rfrl"
  facebook_key: '716327595114703'
  facebook_secret: "5587a9514a86d370c782d5c61cbb0931"
  google_key: "476925498782-d9nvimc4qv7f3ffl1esg0r5rgru51sfa.apps.googleusercontent.com"
  google_secret: "f47QPyfPPvUT7WkAEKRKMKMw"
  logo_home: "uploads/photo/image/16/LOGO-Home_page.png"
  logo_welcome: "uploads/photo/image/17/LOGO-Welcome_page.png"
  upyun:
    username: promokerdev
    password: aWDR89vlVpvH
    bucket: promoker-dev
    bucket_host: http://promoker-dev.b0.upaiyun.com

development:
  <<: *defaults
test:
  <<: *defaults
vagrant:
  <<: *defaults
  faye_server: "http://default.foo.com:8080/faye"
  faye_token: "123456"
  upyun:
    username: promokerstaging
    password: ylNOtF8PPjUy
    bucket: promoker-staging
    bucket_host: http://promoker-staging.b0.upaiyun.com
production:
  <<: *defaults
  faye_server: "http://promoker.com:8080/faye"
  faye_token: "123456"
  upyun:
    username: promoker
    password: Rtoe2GtNo1KO
    bucket: promoker
    bucket_host: http://promoker.b0.upaiyun.com
