development:
  adapter: mysql2
  database: promoker_development
  username: root
  password:
  host: localhost

test:
  adapter: mysql2
  database: promoker_test
  username: root
  password:
  host: localhost

vagrant:
  adapter: mysql2
  database: promoker_vagrant
  username: root
  password:
  host: localhost

production:
  adapter: mysql2
  database: promoker_production
  username: root
  password:
  host: localhost
