development:
  adapter: mysql2
  database: promoker_staging
  username: root
  password:
  host: localhost

test:
  adapter: mysql2
  database: promoker_test
  username: root
  password:
  host: localhost

staging:
  adapter: mysql2
  database: promoker_staging
  username: root
  password:
  host: localhost

production:
  adapter: mysql2
  database: promoker_production
  username: root
  password:
  host: localhost
